// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBughgIYOWTn6Yu-I6UlMRlh3-q9ulxBk',
    appId: '1:595228685506:web:199a037614af9160abb75b',
    messagingSenderId: '595228685506',
    projectId: 'laos-pic',
    authDomain: 'laos-pic.firebaseapp.com',
    storageBucket: 'laos-pic.firebasestorage.app',
    measurementId: 'G-ZT6EGSZ57M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNPwqNVw5q-xkwMLsH4R56RpOSQs-vXA',
    appId: '1:595228685506:android:bf2f14a22a022716abb75b',
    messagingSenderId: '595228685506',
    projectId: 'laos-pic',
    storageBucket: 'laos-pic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkuUKRwKZAN67y8peHaCl9TlXtzXn6Jw',
    appId: '1:595228685506:ios:f5d5ef3843e43567abb75b',
    messagingSenderId: '595228685506',
    projectId: 'laos-pic',
    storageBucket: 'laos-pic.firebasestorage.app',
    iosBundleId: 'com.example.mobileFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkuUKRwKZAN67y8peHaCl9TlXtzXn6Jw',
    appId: '1:595228685506:ios:f5d5ef3843e43567abb75b',
    messagingSenderId: '595228685506',
    projectId: 'laos-pic',
    storageBucket: 'laos-pic.firebasestorage.app',
    iosBundleId: 'com.example.mobileFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBughgIYOWTn6Yu-I6UlMRlh3-q9ulxBk',
    appId: '1:595228685506:web:346f67ab8138c511abb75b',
    messagingSenderId: '595228685506',
    projectId: 'laos-pic',
    authDomain: 'laos-pic.firebaseapp.com',
    storageBucket: 'laos-pic.firebasestorage.app',
    measurementId: 'G-FDQ4Y1KNCE',
  );
}
