// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVEbTL-EeoJMIN4qBajkw7eRXrs7eYZr4',
    appId: '1:979177717842:web:84d0f2f463c2f32e259f8b',
    messagingSenderId: '979177717842',
    projectId: 'tanapoom-shop',
    authDomain: 'tanapoom-shop.firebaseapp.com',
    storageBucket: 'tanapoom-shop.firebasestorage.app',
    measurementId: 'G-Z9H8RETTSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRZoso-nUwb2DCmW5y-yIzuNHLUfBbOs',
    appId: '1:979177717842:android:88f24785fc0ba4ba259f8b',
    messagingSenderId: '979177717842',
    projectId: 'tanapoom-shop',
    storageBucket: 'tanapoom-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7KbW98v4eQg45bZfRMb9Fu4x4Cg-IS5E',
    appId: '1:979177717842:ios:f9d5d25353adb561259f8b',
    messagingSenderId: '979177717842',
    projectId: 'tanapoom-shop',
    storageBucket: 'tanapoom-shop.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7KbW98v4eQg45bZfRMb9Fu4x4Cg-IS5E',
    appId: '1:979177717842:ios:f9d5d25353adb561259f8b',
    messagingSenderId: '979177717842',
    projectId: 'tanapoom-shop',
    storageBucket: 'tanapoom-shop.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVEbTL-EeoJMIN4qBajkw7eRXrs7eYZr4',
    appId: '1:979177717842:web:0c4ef3216b3f27cc259f8b',
    messagingSenderId: '979177717842',
    projectId: 'tanapoom-shop',
    authDomain: 'tanapoom-shop.firebaseapp.com',
    storageBucket: 'tanapoom-shop.firebasestorage.app',
    measurementId: 'G-ECZB1Y2TER',
  );
}
